---
services:
  db:
    image: shaikmustafa/flm2026:dbimage
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  auth:
    image: shaikmustafa/flm2026:authimage
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - db
    

  book:
    image: shaikmustafa/flm2026:bookimage
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on:
      - db
  borrow:
    image: shaikmustafa/flm2026:borrowimage
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    image:shaikmustafa/flm2026:frontend
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth
      - book
      - borrow

networks:
  mynetwork:
    driver: overlay
